### ISSUE TITLE
Strange behavior when using Golang 1.4.2

### ISSUE THREAD

**Issue by calebamiles** [fraenkel/candiedyaml#6]
Hello,

We were seeing some strange behavior when trying to unmarshal the release manifest when using a binary built with Golang 1.4.2. The following release manifest (release.MF inside a BOSH release)

```yaml
---
packages:
- name: bosh_aws_cpi
  version: 2bb22c5a553350eed303a5382d4d557798d48914
  fingerprint: 2bb22c5a553350eed303a5382d4d557798d48914
  sha1: 0910f53d9a2d39586524c62db6daaafed286b754
  dependencies:
  - ruby_aws_cpi
- name: ruby_aws_cpi
  version: 052a28b8976e6d9ad14d3eaec6d3dd237973d800
  fingerprint: 052a28b8976e6d9ad14d3eaec6d3dd237973d800
  sha1: 714721b012d5595fe82ea9b4d3249ec8b81f1111
  dependencies: []
jobs:
- name: cpi
  version: ca1bbc783f6b12eb1d066ac4b54c75fb8351465e
  fingerprint: ca1bbc783f6b12eb1d066ac4b54c75fb8351465e
  sha1: 691b21147d13b96848f1e66a8d14260eebc12527
commit_hash: 5a4f720e
uncommitted_changes: true
name: bosh-aws-cpi
version: '6'
```

fails to unmarshal the `Version` field into the following struct

```go
type Manifest struct {
        Name    string `yaml:"name"`
        Version string `yaml:"version"`

        CommitHash         string `yaml:"commit_hash"`
        UncommittedChanges bool   `yaml:"uncommitted_changes"`

        Jobs     []JobRef     `yaml:"jobs"`
        Packages []PackageRef `yaml:"packages"`
}
```

We see this failure pretty repeatably and to reproduce you can follow the instructions for the [bosh micro CLI](https://github.com/cloudfoundry/bosh-micro-cli) with any release from [bosh hub](bosh.io). If you're not ready for Golang 1.4.2 support then we'll take a note of that and adjust our workstation environments accordingly.

Thanks!

@calebamiles
Pivotal CF BOSH Team
